# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snapshot.proto',
  package='snapshot',
  syntax='proto3',
  serialized_pb=_b('\n\x0esnapshot.proto\x12\x08snapshot\"\x93\x01\n\nimage_data\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x11\n\tdate_time\x18\x03 \x01(\x04\x12\x13\n\x0bsource_host\x18\x04 \x01(\t\x12\x16\n\x0esource_address\x18\x05 \x01(\t\x12\x12\n\nimage_type\x18\x06 \x01(\t\x12\x10\n\x08location\x18\x07 \x01(\t\"(\n\x06result\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05reply\x18\x02 \x01(\t2?\n\tsnap_shot\x12\x32\n\x08\x61\x64\x64_snap\x12\x14.snapshot.image_data\x1a\x10.snapshot.resultb\x06proto3')
)




_IMAGE_DATA = _descriptor.Descriptor(
  name='image_data',
  full_name='snapshot.image_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='snapshot.image_data.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='snapshot.image_data.sequence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_time', full_name='snapshot.image_data.date_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_host', full_name='snapshot.image_data.source_host', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_address', full_name='snapshot.image_data.source_address', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_type', full_name='snapshot.image_data.image_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='snapshot.image_data.location', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=176,
)


_RESULT = _descriptor.Descriptor(
  name='result',
  full_name='snapshot.result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='snapshot.result.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reply', full_name='snapshot.result.reply', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=218,
)

DESCRIPTOR.message_types_by_name['image_data'] = _IMAGE_DATA
DESCRIPTOR.message_types_by_name['result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image_data = _reflection.GeneratedProtocolMessageType('image_data', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE_DATA,
  __module__ = 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:snapshot.image_data)
  ))
_sym_db.RegisterMessage(image_data)

result = _reflection.GeneratedProtocolMessageType('result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:snapshot.result)
  ))
_sym_db.RegisterMessage(result)



_SNAP_SHOT = _descriptor.ServiceDescriptor(
  name='snap_shot',
  full_name='snapshot.snap_shot',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=220,
  serialized_end=283,
  methods=[
  _descriptor.MethodDescriptor(
    name='add_snap',
    full_name='snapshot.snap_shot.add_snap',
    index=0,
    containing_service=None,
    input_type=_IMAGE_DATA,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNAP_SHOT)

DESCRIPTOR.services_by_name['snap_shot'] = _SNAP_SHOT

# @@protoc_insertion_point(module_scope)
